targets:
  $default:
    sources:
      - lib/**
      - $package$
      - graphql/**
    builders:
      artemis:
        generate_for:
          include:
            - lib/**
            - graphql/*.graphql
        options:
          fragments_glob: graphql/**.fragment.graphql
          schema_mapping:
            - output: lib/generated/graphql_api.graphql.dart
              schema: graphql/schema.graphql
              queries_glob: graphql/*.query.graphql
          scalar_mapping:
            - custom_parser_import: "package:graphql_login/data/api/scalar_mapping/coercers.dart"
              graphql_type: ISO8601DateTime
              dart_type: DateTime
            - custom_parser_import: "package:graphql_login/data/api/scalar_mapping/coercers.dart"
              graphql_type: ISO8601Date
              dart_type: DateTime
            - custom_parser_import: "package:graphql_login/data/api/scalar_mapping/coercers.dart"
              graphql_type: JSON
              dart_type: String
            - graphql_type: LongInteger
              dart_type: int
